service: mesh-converter

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: '20201221'
  region: us-west-1

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3003

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: mesh/convert
          method: get
  upload:
    handler: handler.upload
    events:
      - http:
          path: mesh/upload
          method: post
  get_asset:
    handler: handler.get_asset
    events:
      - http:
          path: mesh/get_asset
          method: get
  get_asset_list:
    handler: handler.get_asset_list
    events:
      - http:
          path: mesh/get_asset_list
          method: get          